name: CI

on: [push]

jobs:
  macos_catalina_build_and_test:
    name: macos catalina build and test
    runs-on: macos-10.15
    steps:
      - name: setup
        run: |
            brew tap dreal-deps/ibex
            brew tap dreal/dreal
            brew install dreal --only-dependencies --build-from-source
